### ISSUE TITLE
VASP internal relaxation for CatLearn NEB

### ISSUE THREAD

**Issue by mustafaalsalmi1999** [SUNCAT-Center/CatLearn#101]
Hi all,
I am just wondering if it possible to run CatLearn ML-NEB without using the ASE VASP calculator but using the VASP internal relaxation (I.e. optimizing the initial and final end-points in VASP)

**Comment by mhangaard** [comment]
It should be fine, as long as you use the same DFT parameters. You would want to make sure both initial and final states are "fully minimized". This goes for NEB as well as ML-NEB.

**Comment by mustafaalsalmi1999** [comment]
Thanks Martin
