### ISSUE TITLE
PLOTNEB problem with plot's text positional requirement 

### ISSUE THREAD

**Issue by kimrojas** [SUNCAT-Center/CatLearn#103]
I am currently testing the tutorials, in particular the `tutorials/11_NEB/04_CO_Cu111/nebCO.py`  
Everything ran properly except the PLOTNEB module.   
I encountered the following output:  
```
The ML-NEB algorithm required  19.636363636363637 times less number of function evaluations than the standard NEB algorithm.
Energy barrier: 0.05631016623911789 eV
Traceback (most recent call last):
  File "/home/krojas/student/rai/catlearn_test/test03/nebCO.py", line 137, in <module>
    plotneb(trajectory='ML-NEB.traj', view_path=False)
  File "/home/krojas/APPS/mambaforge/envs/catlearn/lib/python3.10/site-packages/catlearn/optimize/tools.py", line 50, in plotneb
    ax.annotate(s=str(np.round(e_barrier, 3))+' eV',
TypeError: Axes.annotate() missing 1 required positional argument: 'text'
```

Method to replicate:
1. Create conda environent `conda create -n pycatlearn python=3.10 catlearn`
2. Download and run `tutorials/11_NEB/04_CO_Cu111/nebCO.py`

May I ask how to fix this?
Should I specify the matplotlib version ?

**Comment by mhangaard** [comment]
The problem was that matplotlib changed since CatLearn was written. Could I ask you to try again with the latest master?

**Comment by kimrojas** [comment]
Thank you for the clarification. It works properly now.
