### ISSUE TITLE
Broken installation setup.py

### ISSUE THREAD

**Issue by mhoffman** [SUNCAT-Center/CatLearn#36]
This first line does not seem to refer to an actual package. At least the URL does not lead anywhere specific. And it breaks the installation.

https://github.com/SUNCAT-Center/CatLearn/blob/8643e4e2557c93e82fc2581082e6d27bf7b4b7cc/requirements.txt#L1

**Comment by mhangaard** [comment]
`pip install catlearn==0.4.2.dev3` still works

**Comment by mhangaard** [comment]
@mhoffman Try `pip install --upgrade catlearn` now. The issue should be fixed by the update to version 0.4.3

**Comment by mhoffman** [comment]
Yes, that works 👍
