### ISSUE TITLE
Highly pedantic `requirements.txt`

### ISSUE THREAD

**Issue by mhoffman** [SUNCAT-Center/CatLearn#40]
Right now the `requirements.txt` looks as follows:
 
    ase==3.16.0
    click==6.7
    cycler==0.10.0
    decorator==4.3.0
    flask==1.0.2
    h5py==2.7.1
    itsdangerous==0.24
    jinja2==2.10
    kiwisolver==1.0.1
    markupsafe==1.0
    matplotlib==2.2.2
    networkx==2.1.0
    numpy==1.14.3
    pandas==0.23.0 
    pyparsing==2.2.0
    python-dateutil==2.7.3
    pytz==2018.4
    scikit-learn==0.19.1
    scipy==1.1.0
    six==1.11.0
    tqdm==4.23.3
    werkzeug==0.14.1

This means, in order to install CatLearn with `pip install catkit` my system needs to match all the packages down to the patch level or pip will refuse to install it. Point in case, if I upgrade my numpy today I would get version `1.14.4` but pip refuses to install CatLearn in this situation since it thinks that CatLearn requires exactly `1.14.3`. This leaves me with two options: either I downgrade or all my other packages to matches exactly CatLearn (and potentially break other packages) or I have to escape into a virtualenv or docker to spin exactly those versions. Would it be possible to relax some of these version numbers using `>=` or `~=`. `>=` simply fixes the version of greater or equal to the stated number but allows to skip trailing digits. So, `numpy>=1.4` would allow everyting greater or equal than `1.4.0`. `~=` skips one more rank. To quote the essential part of the following website

    Mopidy-Dirble ~= 1.1        # Compatible release. Same as >= 1.1, == 1.*

This website documents the different possible qualifiers https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file . Better yet unless there is a specific reason I would never state the third version number because assuming the depedency sticks to semantic version this would only count the number of patches not break backwards compatibility.

**Comment by mhangaard** [comment]
@mhoffman try upgrading to 0.4.4.dev2. `pip install --upgrade --pre catlearn`
