### ISSUE TITLE
MLNeb hangs with latest ASE from git

### ISSUE THREAD

**Issue by ehermes** [SUNCAT-Center/CatLearn#71]
The tutorial described in `11_NEB/00_Tutorial/Tutorial_MLNEB.ipynb` hangs when using the latest ASE git head due to changes in the `Dynamics` class located in `ase/optimize/optimize.py`. Specifically, this loop can repeat forever:

https://github.com/SUNCAT-Center/CatLearn/blob/2cd306dd494402dbaaef2da38664da719ee8e46d/catlearn/optimize/mlneb.py#L379-L419

This happens when `neb_opt` doesn't immediately converge, because `neb_opt.run(..., steps=1)` now returns before performing any steps if `neb_opt.max_steps` has been reached. Additionally, `neb_opt.nsteps` isn't incremented by `neb_opt.run(...)` beyond `max_steps`, so the bailout condition of `n_steps_performed > ml_steps-1` never evaluates to `True`.

A simple workaround would be to manually set `neb_opt.nsteps = 0` immediately before `neb_opt.run(..)`. There's probably a more elegant way of telling ASE's `NEB` class to iterate once, but that would require more changes to the code, and the workaround I describe seems to work for me.

As an aside, I don't understand why CatLearn accesses `nsteps` through `neb_opt`'s `__dict__` attribute (L407). Is there a reason for this atypical access pattern?

**Comment by jagarridotorres** [comment]
@ehermes Thanks for letting us know. The issue should have been solved in v0.6.1. We have also corrected a few bugs related to I/O.
