### ISSUE TITLE
MLMIN bug with ASE 3.19

### ISSUE THREAD

**Issue by vieri2006** [SUNCAT-Center/CatLearn#92]
There is a major bug in MLMIN when used with ASE 3.19. It behaves like previous NEB bug (if im not mistaken)
The bug is: the iteration of geo_opt using GPR in line 283 doesn't works well

I have compared them when used with ASE 3.17 and 3.19
the one that optimized quickly is done with ASE 3.17
![Screenshot from 2020-07-05 13-54-44](https://user-images.githubusercontent.com/51873615/86527221-1ea32880-bec7-11ea-874b-c8cdad85ef54.png)
![Screenshot from 2020-07-05 12-51-58](https://user-images.githubusercontent.com/51873615/86527224-21058280-bec7-11ea-88fd-0eacf4f59df6.png)

**Comment by vieri2006** [comment]
Some context: the GPR MDMIN part of the catlearn doesn't work if used with ase 3.19
So i found out that ase 3.19 has different MDMIN function than ase 3.17 in the optimizer class

https://gitlab.com/ase/ase/-/blob/3.19.0/ase/optimize/optimize.py#L267
https://gitlab.com/ase/ase/-/blob/3.17.0/ase/optimize/optimize.py#L193

Gonna check it soon

**Comment by vieri2006** [comment]
I have tinkered on it and fixed it in my computer

**Comment by mhangaard** [comment]
Thank you for posting this issue and #91 and #93 
I hope we can get this reviewed soon.
As for MLMin, there is an alternative built natively into ASE called GPMin (https://wiki.fysik.dtu.dk/ase/ase/optimize.html?highlight=gp#ase.optimize.GPMin). In the meantime, I recommend anyone here to try GPMin.

**Comment by mhangaard** [comment]
fixed after #93
